/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"
#include "adc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint16_t adc_output[100];


int main(void)
{
	GPIO_ConfigPin(GPIOA,
	                    1,
						GPIO_ANALOG,
						GPIO_PUSH_PULL,
						GPIO_NO_PULL,
						GPIO_LOW_SPEED);

	ADC_Init(ADC1, ADC_CLOCK_DIV4, Bit_Resolution_6, Right_Alignment,
			Scan_disable, Cont_Conversion, ADC_En);

	ADC_ConfigChannel(ADC1, 1, Cycles_15, conv_seq_1, 1);

	ADC_StartConversion(ADC1);

	uint16_t i = 0;

    /* Loop forever */
	for(;;){
		ADC_WaitForConversion(ADC1);
		adc_output[i] = ADC_ReadData(ADC1);
		i = (i + 1U) % 100U;
	}
}















